export type MuscleGroup =
    | 'chest'
    | 'lats'
    | 'upper_back'
    | 'front_delts'
    | 'side_delts'
    | 'rear_delts'
    | 'biceps'
    | 'triceps'
    | 'quads'
    | 'hamstrings'
    | 'calves'
    | 'adductors'
    | 'erectors'
    | 'core'
    | 'glutes'
